model_params:
  name: 'BetaVAE_CONV'
  in_channels: 3
  latent_dim: 20 # for celeba
  hidden_dims: [32, 64, 128, 256, 512]
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000

exp_params:
  dataset: celeba
  data_path: "./data/"
  img_size: 64
  optimizer: "adam"
  batch_size: 144 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 100
  max_epochs: 100

logging_params:
  save_dir: "logs"
  name: "BetaVAE_B"
  manual_seed: 1265
