model_params:
  name: 'BetaVAE_CONV2'
  in_channels: 1
  latent_dim: 10 
  loss_type: 'B'
  img_size: 64
  gamma: 2000.0
  max_capacity: 20
  Capacity_max_iter: 100000
  # conv_sizes: [4,4,4,4]
  distribution: bernoulli
  recons_multi: 0.02 

exp_params:
  dataset: dsprites
  data_path: "./data/"
  img_size: 64
  optimizer: "adam"
  batch_size: 64 
  LR: 0.0005
  weight_decay: 0.0
  # scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 100

logging_params:
  save_dir: "logs"
  name: "BetaVAE_CONV"
  manual_seed: 1265
