model_params:
  name: 'BetaVAE_CONV'
  in_channels: 3
  latent_dim: 25 
  hidden_dims: [32, 64, 128]
  # loss_type: 'H'
  # beta: 1
  img_size: 64
  loss_type: 'B'
  gamma: 0
  max_capacity: 25
  Capacity_max_iter: 10000

  # distribution: bernoulli
  distribution: multi_class_prob
  # conv_sizes: [7, 5, 5]
  recons_multi: 1

exp_params:
  dataset: codex/HBM443.FDHZ.888/cell_grids_level0_step20_filter
  data_path: "./data/"
  in_channels: 3
  img_size: 64
  item_number: 80 # 0 incidate using all cells
  optimizer: "adam"
  batch_size: 16
  LR: 0.001
  eps: 1e-7
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 100
  max_epochs: 400

logging_params:
  save_dir: "logs"
  name: "BetaVAE_CONV"
  manual_seed: 1265
