model_params:
  name: 'BetaVAE_CONV'
  in_channels: 3
  latent_dim: 20 
  hidden_dims: [32, 64, 128, 256]
  # conv_sizes: [7, 5, 5]
  loss_type: 'B' # H or B
  beta: 1
  img_size: 64
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  distribution: gaussian
  recons_multi: 256
  is_masked: False

exp_params:
  dataset: codex/HBM622.JXWQ.554/cell_grids_level1_step20
  data_path: "./data/"
  img_size: 64
  cell_number: 0 # 0 incidate using all cells
  optimizer: "adam"
  batch_size: 196 
  LR: 0.0005
  eps: 1e-7
  weight_decay: 0.0
  weighted_sampler: True
  # scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 100
  max_epochs: 400

logging_params:
  save_dir: "logs"
  name: "BetaVAE_CONV"
  manual_seed: 1265
