model_params:
  name: 'BetaVAE_CONV'
  in_channels: 3
  latent_dim: 12 
  hidden_dims: [32, 64, 128, 256, 512]
  loss_type: 'B'
  img_size: 50
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  recons_multi: 1
  is_masked: False

exp_params:
  dataset: IDC_regular_ps50_idx5
  data_path: "./data/"
  img_size: 50
  optimizer: "adam"
  batch_size: 196 
  LR: 0.002
  weight_decay: 0.0
  weighted_sampler: True
  # scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 100
  max_epochs: 10

logging_params:
  save_dir: "logs"
  name: "BetaVAE_TAD"
  manual_seed: 1265
