model_params:
  name: 'BetaVAE_TAD'
  in_channels: 1
  latent_dim: 8 # for dsprites
  # latent_dim: 28 # for celeba
  hidden_dims: [16, 64, 256]
  loss_type: 'B'
  img_size: 64
  gamma: 10.0
  max_capacity: 25
  Capacity_max_iter: 10000
  conv_sizes: [7,5,3]

exp_params:
  dataset: TAD_HFFc6_10k_chr1-5
  data_path: "./data/"
  img_size: 64
  optimizer: "adam"
  batch_size: 196 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 1000
  max_epochs: 1000

logging_params:
  save_dir: "logs"
  name: "BetaVAE_TAD"
  manual_seed: 1265
