model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 28
  loss_type: 'H'
  beta: 10.

exp_params:
  dataset: celeba
  data_path: "../../Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 30
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "BetaVAE_H"
  manual_seed: 1265
