model_params:
  name: 'CategoricalVAE'
  in_channels: 3
  latent_dim: 512
  categorical_dim: 40
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 1.0

exp_params:
  dataset: celeba
  data_path: "../../Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [1]
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "CategoricalVAE"
  manual_seed: 1265
