model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 40
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: "../Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
  manual_seed: 1265
