model_params:
  name: 'HVAE'
  in_channels: 3
  latent1_dim: 64
  latent2_dim: 64
  pseudo_input_size: 128

exp_params:
  dataset: celeba
  data_path: "../../Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "VampVAE"
  manual_seed: 1265
